---
- name: Clone, build, and run Java application
  hosts: production
  vars:
    repo_url: "git@github.com:afiffahreza/devops-final-project.git"
  pre_tasks:
    - name: Update all packages
      become: yes
      dnf:
        name: '*'
        state: latest
        update_cache: yes
    - name: Install Java
      become: yes
      dnf:
        name: java-17-amazon-corretto
        state: present
    - name: Install Maven package
      become: yes
      dnf:
        name: maven
        state: present
    - name: Ensure .ssh directory exists
      file:
        path: "~/.ssh"
        state: directory
        mode: '0700'
    - name: Check if id_rsa exists
      stat:
        path: "~/.ssh/id_rsa"
      register: id_rsa_check
    - name: Decode base64 private key and create id_rsa if it does not exist
      shell: |
        export $(grep -v '^#' /opt/env/.env | xargs)
        echo "$GH_DEPLOY_KEY" | base64 -d > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
      when: not id_rsa_check.stat.exists
    - name: Add GitHub to known_hosts
      shell: |
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      args:
        creates: "~/.ssh/known_hosts"
  tasks:
    - name: Stop the currently running Java application
      shell: |
        pkill -f 'mvn spring-boot:run'
      ignore_errors: yes
    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "/tmp/repo"
        update: yes
        key_file: "~/.ssh/id_rsa"
    - name: Change directory to the repository and build the project
      shell: |
        cd /tmp/repo
        mvn clean compile
      args:
        chdir: /tmp/repo
    - name: Run the Java application
      shell: |
        nohup mvn spring-boot:run -Dspring-boot.run.arguments=--server.port=80 > logs/app.log 2>&1 &
        echo $! > app.pid

        echo "Waiting for app to be available at http://localhost:80..."
        for i in $(seq 1 20); do
          if curl -s --head --fail http://localhost:80; then
            echo "App is up!"
            exit 0
          fi
          echo "App not up yet, retrying in 5s... ($i/20)"
          sleep 5
        done

        echo "App did not start in time after 20 attempts."
        echo "Dumping logs from logs/app.log:"
        echo "----------------------------------"
        cat logs/app.log || echo "No logs found!"
        echo "----------------------------------"

        echo "🔪 Killing Spring Boot app process if it's still running..."
        kill $APP_PID || true

        exit 1
      args:
        chdir: /tmp/repo
