services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/jenkins.Dockerfile
    env_file:
      - /opt/env/.env
    # Replace with this if running locally
    # environment:
    #   GH_REPO_URL: ${GH_REPO_URL}
    #   GH_DEPLOY_KEY: ${GH_DEPLOY_KEY}
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
      - ./jenkins/workflows:/var/jenkins_home/workflows
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-network
    depends_on:
      - jenkins

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring-network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false

networks:
  monitoring-network:
    driver: bridge

volumes:
  jenkins_home:
  grafana_data:
